const data = [
  {
    title: "Leicht 1",
    key: "D Major",
    data: "2022",
    collection: "Leichts : Beginner Piano Pieces",
    theme: "Light",
    timSig: "4/4",
    lmw: 1,
    pre: "L",
    col: "indigo",
    desc: "This Piece is in D Major and is a quiet and simple piece.",
    sheetMusicLink: "/leicht1.pdf",
    recordingLink: "https://www.youtube.com/embed/oiziGLe1jBw",
    midiLink: "/leicht1.wav",
  },

  {
    title: "Leicht 2",
    key: "A Minor",
    data: "2022",
    collection: "Leichts : Beginner Piano Pieces",
    theme: "March",
    timSig: "4/4",
    lmw: 2,
    pre: "L",
    col: "indigo",
    desc: "This Piece is in A Minor and it is a sadistic March",
    sheetMusicLink: "/leicht2.pdf",
    recordingLink: "https://www.youtube.com/embed/oiziGLe1jBw",
    midiLink: "/leicht2.mp3",
  },

  {
    title: "Leicht 3",
    key: "C Major",
    data: "2022",
    collection: "Leichts : Beginner Piano Pieces",
    theme: "March",
    timSig: "4/4",
    lmw: 3,
    pre: "L",
    col: "indigo",
    desc: "This Piece is in C Major and it is a happy yet sad march.",
    sheetMusicLink: "/leicht3.pdf",
    recordingLink: "https://www.youtube.com/embed/oiziGLe1jBw",
    midiLink: "/l1.wav",
  },

  {
    title: "Leicht 4",
    key: "E Major",
    data: "2022",
    collection: "Leichts : Beginner Piano Pieces",
    theme: "March",
    timSig: "2/4",
    lmw: 4,
    pre: "L",
    col: "indigo",
    desc: "This Piece is a happy, rhythimic march.",
    sheetMusicLink: "/leicht4.pdf",
    recordingLink: "https://www.youtube.com/embed/oiziGLe1jBw",
    midiLink: "/l1.wav",
  },

  {
    title: "Leicht 5",
    key: "F Major",
    data: "2022",
    collection: "Leichts : Beginner Piano Pieces",
    theme: "Meme",
    timSig: "2/2 and 2/4",
    lmw: 5,
    pre: "L",
    col: "indigo",
    desc: "Yeah this piece is just a massive meme I created on a friend's request.",
    sheetMusicLink: "/leicht5.pdf",
    recordingLink: "https://www.youtube.com/embed/oiziGLe1jBw",
    midiLink: "/l1.wav",
  },

  {
    title: "Leicht 7",
    key: "A Major",
    data: "2022",
    collection: "Leichts : Beginner Piano Pieces",
    theme: "Playground",
    timSig: "3/4",
    lmw: 5,
    pre: "L",
    col: "indigo",
    desc: "This piece is a rag-time playground didy and my first piece with lyrics. This is a classic beginner's piece.",
    sheetMusicLink: "/leicht7.pdf",
    recordingLink: "https://www.youtube.com/embed/oiziGLe1jBw",
    midiLink: "/leicht7.mp3",
  },

  {
    title: "Hooke Sonata",
    key: "A Minor",
    data: "2022",
    collection: "Violin Sonatas",
    theme: "Emotion",
    timSig: "3/4",
    lmw: 5,
    pre: "V",
    col: "orange",
    desc: "This piece is a serious, dramatic yet emotional piece written for violin with piano accompaniment. My first real, serious piece. Dedicated to Robert Hooke.",
    sheetMusicLink: "/verz.pdf",
    recordingLink: "https://www.youtube.com/embed/oiziGLe1jBw",
    midiLink: "/l1.wav",
  },
];

export default data;
